Models/Items.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MLSaleBoard.Models
{
    public class Items
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string ItemName { get; set; }

        public string ItemImg { get; set; }

        [Required]
        public string ItemDesc { get; set; }

        [Required]
        public int ItemPrice { get; set; }

        [Required]
        public string ItemCategory { get; set; }

        [Required]
        public int ItemQuantity { get; set; }

        public string Seller { get; set; }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using MLSaleBoard.Data;
using MLSaleBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MLSaleBoard
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ItemsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        //// GET: ItemsController
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Items.ToListAsync());
        //}

        // GET: Movies
        public async Task<IActionResult> Index(string itemCategory, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> itemCategoryQuery = from m in _context.Items
                                            orderby m.ItemCategory
                                            select m.ItemCategory;

            var items = from i in _context.Items
                         select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.ItemName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(itemCategory))
            {
                items = items.Where(x => x.ItemCategory == itemCategory);
            }

            var itemResults = new ItemSearch
            {
                ItemCategory = new SelectList(await itemCategoryQuery.Distinct().ToListAsync()),
                Items = await items.ToListAsync()
            };

            return View(itemResults);
        }

        // GET: Items/myItems
        public ActionResult MyItems()
        {
            var seller = _userManager.GetUserName(User);

            if (seller == null)
            {
                ViewBag.errorMessage = "You are currently not logged in, please log in!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            if (seller == "Admin@Admin.Com")
            {
                ViewBag.errorMessage = "Admins cannot access this function. Please head to Admin tab to access functionalities!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }


            var items = _context.Items
                .Where(i => i.Seller == seller);
            return View("MyItems", items);
        }

        // GET: Items/myItems
        public async Task<ActionResult> AdminAsync()
        {
            var user = _userManager.GetUserName(User);

            if (user == "Admin@Admin.Com")
            {
                return View(await _context.Items.ToListAsync());
            }

            if (user == null)
            {
                ViewBag.errorMessage = "You are not logged in as an Admin! Please log in!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            ViewBag.errorMessage = "You are not allowed to access this function as you are not logged in as an Admin!";
            return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
        }

        // GET: ItemsController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .FirstOrDefaultAsync(i => i.Id == id);

            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // GET: ItemsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ItemName,ItemImg,ItemDesc,ItemPrice,ItemCategory,ItemQuantity,Posted,LastUpdated")] Items items)
        {
            if (ModelState.IsValid)
            {
                // get the seller
                var seller = _userManager.GetUserName(User);

                if (seller == "Admin@Admin.Com")
                {
                    ViewBag.errorMessage = "Admins cannot access this function. Please head to Admin tab to access functionalities!";
                    return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
                }

                //if not logged in, cannot create item
                if (seller == null)
                {
                    ViewBag.errorMessage = "You are not logged in! Please log in!";
                    return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
                }
                items.Seller = seller;
                _context.Add(items);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(items);
        }

        // GET: ItemsController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = _userManager.GetUserName(User);
            if (user == null)
            {
                ViewBag.errorMessage = "You must be logged in to edit items. Please log in!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            var items = await _context.Items.FindAsync(id);
            if (items == null)
            {
                return NotFound();
            }

            if (user != items.Seller)
            {
                if (user == "Admin@Admin.Com")
                {
                    return View(items);
                }
                ViewBag.errorMessage = "You are not logged in as the user who created the item!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            return View(items);
        }

        // POST: ItemsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ItemName,ItemImg,ItemDesc,ItemPrice,ItemCategory,ItemQuantity,Posted,LastUpdated,Seller")] Items items)
        {
            if (id != items.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(items);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemsExists(items.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(items);
        }

        // GET: ItemsController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .FirstOrDefaultAsync(i => i.Id == id);

            if (items == null)
            {
                return NotFound();
            }

            var loggedInUser = _userManager.GetUserName(User);
            if (items.Seller != loggedInUser)
            {
                if (loggedInUser == "Admin@Admin.Com")
                {
                    return View(items);
                }
                ViewBag.errorMessage = "You can not delete the item as you are not logged in as the user who create the item. Please log in!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            return View(items);
        }

        // POST: ItemsController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var items = await _context.Items.FindAsync(id);
            _context.Items.Remove(items);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: ItemsController/Purchase/5
        public async Task<IActionResult> Purchase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // get the user
            var user = _userManager.GetUserName(User);

            if (user == "Admin@Admin.Com")
            {
                ViewBag.errorMessage = "Admins cannot purchase items, please access Admin tab for admin functionalities!";
                return View("Views/Home/Error.cshtml", ViewBag.errorMessage);
            }

            var items = await _context.Items
                .FirstOrDefaultAsync(i => i.Id == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // POST: ItemsController/Purchase/5
        [HttpPost, ActionName("Purchase")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PurchaseConfirmed([Bind("Item,ItemQuantity")] Sales sales)
        {

            // get the buyer
            var buyer = _userManager.GetUserName(User);
            sales.Buyer = buyer;
  
            // make the sale
            _context.Add(sales);

            // find the item
            var items = await _context.Items

Views/Items/AddToCart.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Purchase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add to cart</h2>

<h3>Are you sure you want to add this to your cart?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemImg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemImg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>
        <dd>
            $@Html.DisplayFor(model => model.ItemPrice)
        </dd>
    </dl>

    <form asp-action="AddToCart">
        <div class="form-group">
            <label asp-for="ItemQuantity" class="control-label"></label>
            <input asp-for="ItemQuantity" class="form-control" />
            <span asp-validation-for="ItemQuantity" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" name="Item" />
        <input type="submit" value="Add to cart" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Items/Admin.cshtml
@model IEnumerable<MLSaleBoard.Models.Items>

@{
    ViewData["Title"] = "My items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Admin: all items</h1>
<p>Please do not forget to log out before exiting the application!</p>

<p>
    <!--<a asp-action="Create">Create New</a>-->
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemImg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemQuantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seller)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemImg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDesc)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.ItemPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemQuantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Items/Create.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Items</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemImg" class="control-label"></label>
                <input asp-for="ItemImg" class="form-control" />
                <span asp-validation-for="ItemImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemDesc" class="control-label"></label>
                <input asp-for="ItemDesc" class="form-control" />
                <span asp-validation-for="ItemDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemPrice" class="control-label"></label>
                <input asp-for="ItemPrice" class="form-control" />
                <span asp-validation-for="ItemPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemCategory" class="control-label"></label>
                <input asp-for="ItemCategory" class="form-control" />
                <span asp-validation-for="ItemCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemQuantity" class="control-label"></label>
                <input asp-for="ItemQuantity" class="form-control" />
                <span asp-validation-for="ItemQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Items/Delete.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemImg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemImg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seller)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seller)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Items/Details.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemImg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemImg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seller)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seller)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Items/Edit.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Items</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemImg" class="control-label"></label>
                <input asp-for="ItemImg" class="form-control" />
                <span asp-validation-for="ItemImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemDesc" class="control-label"></label>
                <input asp-for="ItemDesc" class="form-control" />
                <span asp-validation-for="ItemDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemPrice" class="control-label"></label>
                <input asp-for="ItemPrice" class="form-control" />
                <span asp-validation-for="ItemPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemCategory" class="control-label"></label>
                <input asp-for="ItemCategory" class="form-control" />
                <span asp-validation-for="ItemCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemQuantity" class="control-label"></label>
                <input asp-for="ItemQuantity" class="form-control" />
                <span asp-validation-for="ItemQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seller" class="control-label"></label>
                <input readonly = "readonly" asp-for="Seller" class="form-control" />
                <span asp-validation-for="Seller" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Items/Index.cshtml
@model MLSaleBoard.Models.ItemSearch

@{
    ViewData["Title"] = "All items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All items</h1>

<p>
    <!--<a asp-action="Create">Create New</a>-->
</p>
<form asp-controller="Items" asp-action="Index" method="get">
    <p>
        <select asp-for="ItemCategory" asp-items="Model.ItemCategory">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString">
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemImg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].ItemQuantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items[0].Seller)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemImg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDesc)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.ItemPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemQuantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller)
                </td>
                <td>
                    |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Purchase" asp-route-id="@item.Id">Purchase</a> |
                    <a asp-action="AddToCart" asp-route-id="@item.Id">Add to Cart</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Items/MyItems.cshtml
@model IEnumerable<MLSaleBoard.Models.Items>

@{
    ViewData["Title"] = "My items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>My items</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemImg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemQuantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seller)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemImg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDesc)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.ItemPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemQuantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Items/PaymentConfirmed.cshtml
@{
    ViewData["Title"] = "Payment confirmed";
}

<div class="text-center">
    <h1 class="display-4">Payment confirmed!</h1>
    <p>You have confirmed payment! Please check your purchases for your purchased items!</p>
</div>

Views/Items/Purchase.cshtml
@model MLSaleBoard.Models.Items

@{
    ViewData["Title"] = "Purchase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation</h2>

<h3>Are you sure you want to buy this?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemImg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemImg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>
    </dl>

    <form asp-action="Purchase">
        <div class="form-group">
            <label asp-for="ItemQuantity" class="control-label"></label>
            <input asp-for="ItemQuantity" class="form-control" />
            <span asp-validation-for="ItemQuantity" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" name="Item" />
        <input type="submit" value="Purchase" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>